package forms;

import data.*;
import javax.swing.JDialog;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * <pre>
 * The CustomerInterfaceAdd class
 * extends JPanel to create the Gui for handling adding a Customer.
 * 
 * For example:
 * <code>
 * CustomerInterfaceAdd addc = new CustomerInterfaceAdd(dialog,conn);
 * </code>
 * </pre>
 *
 * @author Riccardo, reviewed and documented by Rudolf.
 * @see javax.swing.JPanel
 * @see data
 * @see models.CustomersTableModel
 */
public class CustomerInterfaceAdd extends javax.swing.JPanel {

    private JDialog dialog = null;
    private DataConnection conn = null;

    /**
     * Creates new JDialog [AddCustomerInterface].
     *
     * @param dialog JDialog
     * @param conn DataConnection
     */
    public CustomerInterfaceAdd(JDialog dialog, DataConnection conn) {
        initComponents();
        this.dialog = dialog;
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        useraddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton = new javax.swing.JToggleButton();
        userpin = new javax.swing.JPasswordField();
        active = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Full name");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel3.setText("Address");

        jLabel4.setText("Pin number");

        jToggleButton.setText("Add new customer");
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        userpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpinActionPerformed(evt);
            }
        });

        active.setSelected(true);
        active.setText("Active");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(useraddress)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(username)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userpin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(active)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useraddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(active))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButtonActionPerformed
    {//GEN-HEADEREND:event_jToggleButtonActionPerformed
        dialog.dispose();
        dialog.setVisible(false);
    }//GEN-LAST:event_jToggleButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void userpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpinActionPerformed

    /**
     * get the Customer Name
     * @return String
     */
    public String getUsername() {
        return username.getText();
    }

    /**
     * Get the Customer Address
     * @return String
     */
    public String getUserAddress() {
        return useraddress.getText();
    }

    /**
     * get the Customer Pin
     * @return String
     */
    public String getUserpin() {
        return String.valueOf(userpin.getPassword());
    }
    
    public boolean getUserActive() {
        return active.isEnabled();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton active;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JTextField useraddress;
    private javax.swing.JTextField username;
    private javax.swing.JPasswordField userpin;
    // End of variables declaration//GEN-END:variables

}
