package forms;

import data.*;
import elements.*;
import javax.swing.JDialog;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * <pre>
 * The CustomerInterfaceEdit class
 * extends JPanel to create the Gui for handling adding a Customer.
 *
 * For example:
 * <code>
 * CustomerInterfaceAdd addc = new CustomerInterfaceAdd(dialog,conn);
 * </code>
 * </pre>
 *
 * @author Riccardo, reviewed and documented by Rudolf.
 * @see javax.swing.JPanel
 * @see data
 * @see elements.Customer
 * @see models.CustomersTableModel
 */
public class CustomerInterfaceEdit extends javax.swing.JPanel {

    private JDialog dialog = null;
    private DataConnection conn = null;
    private Customer customer = null;
	private boolean commitChanges = false;

    /**
     * Creates new form CustomerInterfaceEdit
     *
     * @param dialog
     * @param conn
     * @param customer
     */
    public CustomerInterfaceEdit(JDialog dialog, DataConnection conn, Customer customer) {
        initComponents();
        this.dialog = dialog;
        this.conn = conn;
        this.customer = customer;
        username.setText(customer.getUserName());
        useraddress.setText(customer.getUserAddress());
        userpin.setText(customer.getUserPin());
        active.setSelected(customer.isActive());
		commitChanges = false;
        //customer.isActive()active.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        userpin = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        useraddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        active = new javax.swing.JRadioButton();

        jToggleButton.setText("Commit changes");
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Full name");

        userpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpinActionPerformed(evt);
            }
        });

        jLabel7.setText("Pin number");

        jLabel8.setText("Address");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        active.setSelected(true);
        active.setText("Active");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useraddress)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(active)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userpin)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useraddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(active)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButtonActionPerformed
    {//GEN-HEADEREND:event_jToggleButtonActionPerformed
        commitChanges = true;
		dialog.dispose();
        dialog.setVisible(false);
    }//GEN-LAST:event_jToggleButtonActionPerformed

    private void userpinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userpinActionPerformed
    {//GEN-HEADEREND:event_userpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpinActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usernameActionPerformed
    {//GEN-HEADEREND:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * get the Customer Name.
     *
     * @return String
     */
    public String getUsername() {
        return username.getText();
    }

    /**
     * Get the Customer Address.
     *
     * @return String
     */
    public String getUseraddress() {
        return useraddress.getText();
    }

    /**
     * Get the Customer Pin
     *
     * @return String
     */
    public String getUserpin() {
        return new String(userpin.getPassword());
        //return (String)userpin.getPassword().toString();
    }

     /**
     * Get the Customer Active
     *
     * @return boolean
     */
    public boolean isUserActive() {
        return active.isSelected();
    }
	
	/**
	 * @return the commitChanges
	 */
	public boolean isCommitChanges()
	{
		return commitChanges;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton active;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JTextField useraddress;
    private javax.swing.JTextField username;
    private javax.swing.JPasswordField userpin;
    // End of variables declaration//GEN-END:variables

}
