DROP TABLE IF EXISTS RECEIPT; 
DROP TABLE IF EXISTS PURCHASE; 
DROP TABLE IF EXISTS CUSTOMER; 
DROP TABLE IF EXISTS PRODUCT; 

CREATE TABLE CUSTOMER (
 USERID INTEGER NOT NULL AUTO_INCREMENT, 
 USERNAME VARCHAR(50) NOT NULL , 
 USERRFID VARCHAR(20) , 
 USERADDRESS VARCHAR(30) , 
 USERPIN VARCHAR(4) 
, CONSTRAINT CUSTOMER_PK PRIMARY KEY (USERID));

CREATE TABLE PRODUCT (
 PRODID INTEGER NOT NULL AUTO_INCREMENT, 
 PRODNAME VARCHAR(50) , 
 PRODRFID VARCHAR(20) , 
 PRODCOST DOUBLE , 
 PRODPRICE DOUBLE,
 PRODTHRESHOLD INT 
, CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODID));

CREATE TABLE PURCHASE (
 PRODID INTEGER NOT NULL , 
 RECEID INTEGER NOT NULL , 
 PURCCOST DOUBLE NOT NULL , 
 PURCQTY INT NOT NULL 
, CONSTRAINT PURCHASE_PK PRIMARY KEY (RECEID, PRODID));

CREATE TABLE RECEIPT (
 RECEID INTEGER NOT NULL AUTO_INCREMENT, 
 USERID INTEGER NOT NULL , 
 RECEDATE DATE DEFAULT NULL 
, CONSTRAINT ORDER_PK PRIMARY KEY (RECEID));

ALTER TABLE PURCHASE ADD CONSTRAINT PURCHASE_PRODUCT_FK FOREIGN KEY (PRODID)
 REFERENCES PRODUCT (PRODID);

ALTER TABLE PURCHASE ADD CONSTRAINT PURCHASE_RECEIPT_FK FOREIGN KEY (RECEID)
 REFERENCES RECEIPT (RECEID);

ALTER TABLE RECEIPT ADD CONSTRAINT RECEIPT_CUSTOMER_FK FOREIGN KEY (USERID)
 REFERENCES CUSTOMER (USERID);