/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serial;

import java.util.Arrays;
import java.util.EventObject;

/**
 *
 * The <code>FrameEvent</code> class represents an event generated by the 
 * <code>SerialFrame</code> class when a complete byte array has been received
 * at the serial port.
 * @version 16/02/10
 * @author ibr
 */
public class FrameEvent extends EventObject {

    private final byte[] byteFrame;

    /**
     * Constructs a <code>FrameEvent</code> object.
     * @param o the object on which the event initially occurred
     * @param byteFrame the data encapsulated by the event.
     */
    public FrameEvent(Object o, byte[] byteFrame) {
        super(o);
        this.byteFrame = Arrays.copyOf(byteFrame, byteFrame.length);
    }

    /**
     * Gets the data string from the frame.
     * @return the data string
     */
    public byte[] getData() {
        return Arrays.copyOf(byteFrame, byteFrame.length);
    }
}
